1. What is a Python library? Why do we use Python libraries?

""" A python library is a collection of code that makes everyday task more efficient.
For example : Using Numpy we can solve numerical problems easily.
We use python libraries becouse they provide wide range of tools and modules for various tasks,
making it easier for developers to work on specific tasks without reinventing the wheel."""

2. What is the difference between Numpy array and List?

The main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of the objects. For example, a NumPy array of strings can only contain strings and no other data types, but a Python list can contain a mixture of strings, numbers, booleans and other objects.

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [7]:
import numpy as np
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
arr
arr.shape #to find the shape of an array
arr.size  #to find size of an array
arr.ndim  #to find dimension of an array 

2

4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [11]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [16]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[2,3] #by this method you can easily asses the element at any point

12

6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [34]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
odd_indexed_elements=arr[0::2]
odd_indexed_elements #This code will provide you odd_indexed_element

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [66]:
import random
arr=np.random.rand(3,3)
arr

array([[0.75109421, 0.00177461, 0.82743502],
       [0.70521471, 0.40167155, 0.60802985],
       [0.98215545, 0.68754251, 0.17707243]])

8. Describe the difference between np.random.rand and np.random.randn?

In [ ]:
"""np.random.rand generates random values from a uniform distribution over [0, 1),
while np.random.randn generates random values from a standard normal distribution (mean=0, standard deviation=1)."""

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [94]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr.reshape(1,1,1,4,3)


array([[[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]]]]])

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [95]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr.T #Through this way we can transpose the given array 

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1
1 Index wise multiplication
2 Matrix multiplication
3 Add both the matrics
4 Subtract matrix B from A
5 Divide Matrix B by A

In [106]:
A2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
B2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

#1 for index wise multiplication we use
index_mul =A2 * B2
index_mul

#2 for matrix wise multiplication we use
matrix_mul =A2 @ B2
matrix_mul

#3 Add both the matrix
add_matrix = A2 + B2
add_matrix

#4 Subtract Both matrix
Sub_matrix = A2 - B2
Sub_matrix

#5 Divide Both Matrix

Div_matrix = A2 / B2
Div_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12.  Which function in Numpy can be used to swap the byte order of an array?

In [111]:
"""In NumPy, we can use the "byteswap" method of an ndarray to swap the byte order"""
#Example
arr = np.array([1, 2, 3, 4],dtype=np.int32)
swapped_array = arr.byteswap()
print("Original Array:", original_array)
print("Swapped Array:", swapped_array)

Original Array: [1 2 3 4]
Swapped Array: [16777216 33554432 50331648 67108864]


13.  What is the significance of the np.linalg.inv function?

In [112]:
"""The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix,
allowing solutions to linear systems of equations and aiding in eigenvalue problems.
It plays a crucial role in various numerical computations."""

'The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix,\nallowing solutions to linear systems of equations and aiding in eigenvalue problems.\nIt plays a crucial role in various numerical computations.'

14. What does the np.reshape function do, and how is it used?

In [119]:
"""The np.reshape function in NumPy is used to change the shape of an array without altering its data.
It takes the original array and the desired new shape as arguments, returning a new array with the specified shape."""

#Example
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr.reshape(1,1,2,3,2)

array([[[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 7,  8],
          [ 9, 10],
          [11, 12]]]]])

15. What is broadcasting in Numpy?

In [120]:
"""Broadcasting in NumPy is the ability to perform element-wise operations on
arrays with different shapes, automatically extending or "broadcasting" smaller arrays to match the shape of larger ones.
This simplifies operations and makes code more concise."""

'Broadcasting in NumPy is the ability to perform element-wise operations on\narrays with different shapes, automatically extending or "broadcasting" smaller arrays to match the shape of larger ones.\nThis simplifies operations and makes code more concise.'